[package]
name = "mnemonic"
version = "0.0.1"
edition = "2021"

[dependencies]
derive-new = "~0.5"
tinyvec = "~1.5"
derive_more = "~0.99"
getset = "~0.1"
rand = "~0.8"
rust-embed = "~6.3"
once_cell = "~1.9"
