[package]
name = "mnemonic"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-embed = "~6.3"
once_cell = "~1.9"
bytes = "~1.1"
num-traits = "~0.2"
num-bigint = "~0.4"
sha2 = "~0.10"
hmac = "~0.12"
pbkdf2 = { version = "~0.10", default-features = false }
unicode-normalization = "~0.1"
