name: Make Release Branch
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      release_from:
        required: true
        default: "develop"

env:
    BRANCH_NAME: release/${{ github.event.inputs.version }}
    FROM: ${{ github.event.inputs.release_from }}

jobs:
  mk_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: checkout and push
        run: |
          git config --global user.name 'Make Release Branch'
          git config --global user.email ''
          git checkout -b ${BRANCH_NAME} ${FROM}
          git push

      - name: make pull request
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          GIT_PR_RELEASE_BRANCH_STAGING: ${BRANCH_NAME}
          GIT_PR_RELEASE_LABELS: ${{ github.event.inputs.version }}
