name: Release Branch
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      release_from:
        required: true
        default: "origin/develop"

jobs:
  mk_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: checkout and push
        run: |
          git config --global user.name 'Make Release Branch'
          git config --global user.email ''
          git fetch
          git checkout ${FROM}
          git checkout -b ${BRANCH_NAME}
          git push -f --set-upstream origin ${BRANCH_NAME}
        env:
            BRANCH_NAME: release/${{ github.event.inputs.version }}
            FROM: ${{ github.event.inputs.release_from }}


      - name: make pull request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: release/${{ github.event.inputs.version }}
          destination_branch: main
          pr_title: Release ${{ github.event.inputs.version }}
